name: "Ubuntu jenkins docker CI workflow"


on:
  push:
    branches: [ main ]
  schedule:
      - cron:  '0 0 * * 0' #At 00:00 on Sunday every week

jobs:

          

  ubuntu-1804-nagios-docker-job:
    name: "ubuntu-18.04 makefile"
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status   
    - name: "make build"
      run: make build      
    - name: "make run"
      run: make run       
    - name: "make teardown"
      run: make teardown 

  ubuntu-2004-nagios-docker-job:
    name: "ubuntu-20.04 makefile"
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status   
    - name: "make build"
      run: make build      
    - name: "make run"
      run: make run       
    - name: "make teardown"
      run: make teardown    

#https://support.nagios.com/kb/article/nagios-core-installing-nagios-core-from-source-96.html#Ubuntu
  ubuntu-1604-nagios-docker-job:
    name: "ubuntu-latest makefile"
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status    
    - name: "make build"
      run: make build      
    - name: "make run"
      run: make run       
    - name: "make teardown"
      run: make teardown       